In [4]:
import re

import nltk
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import BertTokenizer, BertModel

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from torch.utils.data import DataLoader, Dataset
from torchtext.data.utils import get_tokenizer

# Download required NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
/usr/local/lib/python3.10/dist-packages/torchtext/data/__init__.py:4: UserWarning:
/!\ IMPORTANT WARNING ABOUT TORCHTEXT STATUS /!\
Torchtext is deprecated and the last released version will be 0.18 (this one). You can silence this warning by calling the following at the beginnign of your scripts: `import torchtext; torchtext.disable_torchtext_deprecation_warning()`
  warnings.warn(torchtext._TORCHTEXT_DEPRECATION_MSG)

In [3]:
tickets_df = pd.read_csv("/content/cleaned_tickets_v4.csv")
tickets_df

,ticket_number,message,tags
0,21,Hi! What is your pricing? Can I talk with some...,Sales
1,22,"Hi, how much is Atlas? Looks like it, yeah.",Sales
2,30,hey not super urgent but fyi in ramp bank you ...,Feature Request
3,39,some minor feedback - i seem to need to sign i...,Feature Request
4,42,Hello! Just came across your site: do you offe...,Feature Request
...,...,...,...
744,1522,"Good morning, everyone. A customer contacted u...",Bug
745,1523,Hey quick question - we are figuring out how t...,Feature Request
746,1524,Hi - I'm running into an issue where there are...,Bug
747,1525,Hey @Rahul Asati!It looks like we are still ge...,Bug
748,1528,"Good morning, everyone. Atlas is running quite...",Bug

In [6]:
# Text cleaning and preprocessing function
def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text.lower())  # Remove punctuation and lowercase
    tokens = tokenizer(text)
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words]  # Lemmatize and remove stop words
    return ' '.join(tokens)

# Initialize the tokenizer, lemmatizer, and stop words
tokenizer = get_tokenizer("basic_english")
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# Clean the text
tickets_df['cleaned_message'] = tickets_df['message'].apply(clean_text)
tickets_df

,ticket_number,message,tags,cleaned_message
0,21,Hi! What is your pricing? Can I talk with some...,Sales,hi pricing talk someone hi yes wed love hop ph...
1,22,"Hi, how much is Atlas? Looks like it, yeah.",Sales,hi much atlas look like yeah
2,30,hey not super urgent but fyi in ramp bank you ...,Feature Request,hey super urgent fyi ramp bank show merriam we...
3,39,some minor feedback - i seem to need to sign i...,Feature Request,minor feedback seem need sign often service ca...
4,42,Hello! Just came across your site: do you offe...,Feature Request,hello came across site offer remote control we...
...,...,...,...,...
744,1522,"Good morning, everyone. A customer contacted u...",Bug,good morning everyone customer contacted u via...
745,1523,Hey quick question - we are figuring out how t...,Feature Request,hey quick question figuring sell 245 support l...
746,1524,Hi - I'm running into an issue where there are...,Bug,hi im running issue chattickets closed filter ...
747,1525,Hey @Rahul Asati!It looks like we are still ge...,Bug,hey rahul asatiit look like still getting gibb...
748,1528,"Good morning, everyone. Atlas is running quite...",Bug,good morning everyone atlas running quite slow...

In [8]:
# Encode the labels
label_encoder = LabelEncoder()
tickets_df["tags"] = label_encoder.fit_transform(tickets_df["tags"])

# Initialize the tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Tokenize the text
def tokenize_text(text, tokenizer, max_length=20):
    return tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )


# Custom Dataset
class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        tokens = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=20,
            return_tensors="pt",
        )
        return {
            "input_ids": tokens["input_ids"].squeeze(0),
            "attention_mask": tokens["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long),
        }

# Build the model
class TextClassificationModel(nn.Module):
    def __init__(self, num_classes):
        super(TextClassificationModel, self).__init__()
        self.bert = BertModel.from_pretrained("bert-base-uncased")
        self.dropout = nn.Dropout(0.3)
        self.linear = nn.Linear(768, num_classes)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls_output = outputs.last_hidden_state[
            :, 0, :
        ]  # Extract the [CLS] token's output
        cls_output = self.dropout(cls_output)
        logits = self.linear(cls_output)
        return logits

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [9]:
# Prepare the data
X_train, X_test, y_train, y_test = train_test_split(
    tickets_df["cleaned_message"], tickets_df["tags"], test_size=0.2, random_state=42
)

train_dataset = TextDataset(X_train.tolist(), y_train.tolist(), tokenizer)
test_dataset = TextDataset(X_test.tolist(), y_test.tolist(), tokenizer)

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=2)


num_classes = len(label_encoder.classes_)
model = TextClassificationModel(num_classes)

# Training the model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = optim.Adam(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [10]:
def train_model(model, train_loader, optimizer, criterion, device, epochs=3):
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for batch in train_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            optimizer.zero_grad()
            outputs = model(input_ids, attention_mask)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
        print(f"Epoch {epoch + 1}, Loss: {total_loss / len(train_loader)}")


train_model(model, train_loader, optimizer, criterion, device, 10)

Epoch 1, Loss: 1.433707826534907
Epoch 2, Loss: 1.1193377734720706
Epoch 3, Loss: 0.7307297830531995
Epoch 4, Loss: 0.31696219347417354
Epoch 5, Loss: 0.1569795403784762
Epoch 6, Loss: 0.09199181155456851
Epoch 7, Loss: 0.12108770757680759
Epoch 8, Loss: 0.07067600588159015
Epoch 9, Loss: 0.05490441833855584
Epoch 10, Loss: 0.01897316345459937

In [11]:
# Evaluate the model
def evaluate_model(model, test_loader, device):
    model.eval()
    correct_predictions = 0
    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_ids, attention_mask)
            _, preds = torch.max(outputs, dim=1)
            correct_predictions += torch.sum(preds == labels).item()
    return correct_predictions / len(test_dataset)


accuracy = evaluate_model(model, test_loader, device)
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.49333333333333335

In [12]:
# Predict on new data
def predict(model, tokenizer, text, device):
    model.eval()
    tokens = tokenizer(
        text, padding="max_length", truncation=True, max_length=20, return_tensors="pt"
    )
    input_ids = tokens["input_ids"].to(device)
    attention_mask = tokens["attention_mask"].to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask)
        _, preds = torch.max(outputs, dim=1)

    return preds.cpu().numpy()


new_messages = ["Can you provide a pricing quote?", "I have a feature suggestion."]
predictions = [predict(model, tokenizer, msg, device)[0] for msg in new_messages]
predicted_labels = label_encoder.inverse_transform(predictions)

print(predicted_labels)

['Spam' 'Feature Request']